name: crafty_bay
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_svg: ^2.2.3
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  logger: ^2.6.2
  http: ^1.6.0
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/


